# uniencoder config
uniencoder_cfg_path: /home/wren93/genads_models/tree/wren93/assets/model_configs/sigvae2_so400m_wan2_2_512.yaml
uniencoder_ckpt_path: null
uniencoder_feature_layer: -2 # could be some integer or "post_norm"
uniencoder_init_vae_decoder: False
uniencoder_attention_implementation: sdpa

# Showo2-qwen config
llm_model_path: /home/wren93/genads_models/tree/zhiheng/models/show/showlab/
frozen_params: ['vae']  # from 498
# frozen_params: null
hidden_size: 1536
image_latent_dim: 48

image_latent_height: 32
image_latent_width: 32
hq_image_latent_height: 64
hq_image_latent_width: 64
mixed_modal_latent_height: 32
mixed_modal_latent_width: 32
patch_size: 1
add_time_embeds: True
add_aspect_ratio_embeds: False
clip_latent_dim: 1152
flow_head_num: 40
mrope_type: dit_3drope_mm
reshape_frame_to_batch_dim: False
attention_backend: flexattention

# transport config
path_type: "Linear"
prediction: "velocity"
loss_weight: null
train_eps: null
sample_eps: null
snr_type: "lognorm"
sampling_method: "euler"
guidance_scale: 7.5
num_inference_steps: 50
atol: 1e-6
rtol: 1e-3
reverse: False
do_shift: True
time_shifting_factor: 3.0

# training config
ntp_coeff: 0.2
flow_coeff: 1.0
und_max_t0: 1.0
use_disp: False
load_stage1_model: null
gradient_checkpointing: True
gradient_checkpointing_kwargs:
  use_reentrant: False
